a = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT', 'SUIUSDT', 'ADAUSDT', 'ENAUSDT', 'LINKUSDT', 'HBARUSDT', 'LTCUSDT', 'XLMUSDT', 'WIFUSDT', 'BNBUSDT', 'ONDOUSDT', 'AAVEUSDT', 'WLDUSDT', 'AVAXUSDT', 'JUPUSDT', 'DOTUSDT', 'TRXUSDT', 'FILUSDT', 'ALGOUSDT', 'ZENUSDT', 'TIAUSDT', 'CRVUSDT', 'AGLDUSDT', 'POPCATUSDT', 'GALAUSDT', 'NEARUSDT']
b = ['ARUSDT', 'BCHUSDT', 'COMPUSDT', 'DASHUSDT', 'DEFIUSDT', 'EGLDUSDT', 'ENSUSDT', 'ETCUSDT', 'GMXUSDT', 'ILVUSDT', 'INJUSDT', 'KSMUSDT', 'MKRUSDT', 'MOVEUSDT', 'QNTUSDT', 'SSVUSDT', 'TRBUSDT', 'XMRUSDT', 'YFIUSDT', 'ZECUSDT']




for i in b:
    if  b not in a:
        print(i)